# Generated by Django 5.0.4 on 2024-07-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='location',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='pincode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
