# Generated by Django 5.0.4 on 2024-07-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0004_payment_location_payment_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
    ]
