# Generated by Django 5.0.4 on 2024-07-22 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0006_cartpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartpayment',
            name='usrdetail',
        ),
        migrations.AddField(
            model_name='payment',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='fapp.addproduct'),
            preserve_default=False,
        ),
    ]
