# Generated by Django 5.0.4 on 2024-07-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0007_remove_cartpayment_usrdetail_payment_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
