# Generated by Django 5.0.4 on 2024-07-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0008_alter_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartpayment',
            name='farmer',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='cartpayment',
            name='fremail',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='cartpayment',
            name='pdctdetails',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='cartpayment',
            name='priceitm',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='cartpayment',
            name='qty',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='cartpayment',
            name='qtyprice',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='cartpayment',
            name='totalprice',
            field=models.IntegerField(default=0),
        ),
    ]
