# Generated by Django 5.0.6 on 2024-08-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0011_frorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cartpayment',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
